// storefront-nuxt/app/components/checkout/Shipping.vue
<script setup lang="ts">
import { convertToLocale } from '~/utils/money'
import { getApiErrorMessage } from '~/utils/api-error'

const PICKUP_OPTION_ON = '__PICKUP_ON'
const PICKUP_OPTION_OFF = '__PICKUP_OFF'

interface ShippingMethod {
  id: string
  name: string
  amount?: number
  price_type?: 'flat' | 'calculated' | string
  insufficient_inventory?: boolean
  service_zone?: {
    fulfillment_set?: {
      type?: string
      location?: {
        address?: Record<string, string | undefined> | null
      } | null
    }
  }
}

const props = defineProps<{
  availableShippingMethods: ShippingMethod[]
}>()

const { cart, setShippingMethod } = useCart()
const route = useRoute()
const router = useRouter()

const isOpen = computed(() => route.query.step === 'delivery')
const selectedId = ref<string | null>(null)
const isLoading = ref(false)
const isLoadingPrices = ref(true)
const error = ref('')
const showPickupOptions = ref(PICKUP_OPTION_OFF)
const calculatedPricesMap = ref<Record<string, number>>({})

const shippingMethods = computed(() =>
  (props.availableShippingMethods ?? []).filter(method => method.service_zone?.fulfillment_set?.type !== 'pickup')
)
const pickupMethods = computed(() =>
  (props.availableShippingMethods ?? []).filter(method => method.service_zone?.fulfillment_set?.type === 'pickup')
)
const hasPickupOptions = computed(() => pickupMethods.value.length > 0)
const currencyCode = computed(() => cart.value?.currency_code || 'usd')

function formatAddress(address: Record<string, string | undefined> | null | undefined) {
  if (!address) {
    return ''
  }

  let value = ''

  if (address.address_1) {
    value += ` ${address.address_1}`
  }

  if (address.address_2) {
    value += `, ${address.address_2}`
  }

  if (address.postal_code) {
    value += `, ${address.postal_code} ${address.city}`
  }

  if (address.country_code) {
    value += `, ${address.country_code.toUpperCase()}`
  }

  return value
}

function getCalculatedPrice(optionId: string) {
  return calculatedPricesMap.value[optionId] ?? 0
}

async function loadCalculatedPrices() {
  isLoadingPrices.value = true

  const methods = shippingMethods.value.filter(method => method.price_type === 'calculated')
  if (!methods.length) {
    calculatedPricesMap.value = {}
    isLoadingPrices.value = false
    return
  }

  const results = await Promise.allSettled(methods.map(async (method) => {
    const option = await $fetch<{ id?: string, amount?: number }>('/api/cart/shipping-option-price', {
      method: 'POST',
      body: { option_id: method.id }
    })

    return { id: option.id || method.id, amount: option.amount }
  }))

  const priceMap: Record<string, number> = {}

  for (const result of results) {
    if (result.status === 'fulfilled' && typeof result.value.amount === 'number') {
      priceMap[result.value.id] = result.value.amount
    }
  }

  calculatedPricesMap.value = priceMap
  isLoadingPrices.value = false
}

function syncSelectedState() {
  selectedId.value = cart.value?.shipping_methods?.at(-1)?.shipping_option_id || null
  showPickupOptions.value = pickupMethods.value.find(method => method.id === selectedId.value)
    ? PICKUP_OPTION_ON
    : PICKUP_OPTION_OFF
}

watch(() => [props.availableShippingMethods, cart.value?.shipping_methods?.at(-1)?.shipping_option_id] as const, async () => {
  syncSelectedState()
  await loadCalculatedPrices()
}, { immediate: true, deep: true })

async function handleSetShippingMethod(id: string, variant: 'shipping' | 'pickup') {
  error.value = ''

  if (variant === 'pickup') {
    showPickupOptions.value = PICKUP_OPTION_ON
  } else {
    showPickupOptions.value = PICKUP_OPTION_OFF
  }

  const previousId = selectedId.value
  selectedId.value = id
  isLoading.value = true

  try {
    await setShippingMethod(id, cart.value?.id)
  } catch (nextError: unknown) {
    selectedId.value = previousId
    error.value = getApiErrorMessage(nextError, 'Failed to set shipping method')
  } finally {
    isLoading.value = false
  }
}

function handleEdit() {
  router.push({ query: { step: 'delivery' } })
}

function handleContinue() {
  router.push({ query: { step: 'payment' } })
}

function handlePickupToggle() {
  const nextMethod = pickupMethods.value.find(option => !option.insufficient_inventory)?.id

  if (nextMethod) {
    handleSetShippingMethod(nextMethod, 'pickup')
  }
}

watch(isOpen, () => {
  error.value = ''
})
</script>

<template>
  <div class="bg-white">
    <div class="flex flex-row items-center justify-between mb-6">
      <h2
        :class="[
          'flex flex-row text-3xl-regular gap-x-2 items-baseline',
          {
            'opacity-50 pointer-events-none select-none': !isOpen && (cart?.shipping_methods?.length ?? 0) === 0
          }
        ]"
      >
        Delivery
        <UIcon
          v-if="!isOpen && (cart?.shipping_methods?.length ?? 0) > 0"
          name="i-lucide-check-circle-2"
          class="text-ui-fg-interactive"
        />
      </h2>
      <button
        v-if="!isOpen && cart?.shipping_address && cart?.billing_address && cart?.email"
        class="text-ui-fg-interactive hover:text-ui-fg-interactive-hover"
        data-testid="edit-delivery-button"
        @click="handleEdit"
      >
        Edit
      </button>
    </div>

    <template v-if="isOpen">
      <div class="grid">
        <div class="flex flex-col">
          <span class="font-medium txt-medium text-ui-fg-base">
            Shipping method
          </span>
          <span class="mb-4 text-ui-fg-muted txt-medium">
            How would you like your order delivered
          </span>
        </div>
        <div data-testid="delivery-options-container">
          <div class="pb-8 md:pt-0 pt-2">
            <button
              v-if="hasPickupOptions"
              type="button"
              data-testid="delivery-option-radio"
              :class="[
                'flex items-center justify-between text-small-regular cursor-pointer py-4 border rounded-rounded px-8 mb-2 hover:shadow-borders-interactive-with-active w-full text-left',
                { 'border-ui-border-interactive': showPickupOptions === PICKUP_OPTION_ON }
              ]"
              @click="handlePickupToggle"
            >
              <div class="flex items-center gap-x-4">
                <div
                  class="size-4 rounded-full border-2 flex items-center justify-center"
                  :class="showPickupOptions === PICKUP_OPTION_ON ? 'border-ui-fg-base' : 'border-gray-300'"
                >
                  <div
                    v-if="showPickupOptions === PICKUP_OPTION_ON"
                    class="size-2 rounded-full bg-ui-fg-base"
                  />
                </div>
                <span class="text-base-regular">
                  Pick up your order
                </span>
              </div>
              <span class="justify-self-end text-ui-fg-base">
                -
              </span>
            </button>

            <button
              v-for="option in shippingMethods"
              :key="option.id"
              type="button"
              data-testid="delivery-option-radio"
              :disabled="option.price_type === 'calculated' && !isLoadingPrices && typeof calculatedPricesMap[option.id] !== 'number'"
              :class="[
                'flex items-center justify-between text-small-regular cursor-pointer py-4 border rounded-rounded px-8 mb-2 hover:shadow-borders-interactive-with-active w-full text-left',
                {
                  'border-ui-border-interactive': option.id === selectedId,
                  'hover:shadow-none cursor-not-allowed': option.price_type === 'calculated' && !isLoadingPrices && typeof calculatedPricesMap[option.id] !== 'number'
                }
              ]"
              @click="handleSetShippingMethod(option.id, 'shipping')"
            >
              <div class="flex items-center gap-x-4">
                <div
                  class="size-4 rounded-full border-2 flex items-center justify-center"
                  :class="option.id === selectedId ? 'border-ui-fg-base' : 'border-gray-300'"
                >
                  <div
                    v-if="option.id === selectedId"
                    class="size-2 rounded-full bg-ui-fg-base"
                  />
                </div>
                <span class="text-base-regular">
                  {{ option.name }}
                </span>
              </div>
              <span class="justify-self-end text-ui-fg-base">
                <template v-if="option.price_type === 'flat'">
                  {{ convertToLocale({ amount: option.amount ?? 0, currency_code: currencyCode }) }}
                </template>
                <template v-else-if="typeof calculatedPricesMap[option.id] === 'number'">
                  {{ convertToLocale({ amount: getCalculatedPrice(option.id), currency_code: currencyCode }) }}
                </template>
                <template v-else-if="isLoadingPrices">
                  <UIcon
                    name="i-lucide-loader-2"
                    class="animate-spin"
                  />
                </template>
                <template v-else>
                  -
                </template>
              </span>
            </button>
          </div>
        </div>
      </div>

      <div
        v-if="showPickupOptions === PICKUP_OPTION_ON"
        class="grid"
      >
        <div class="flex flex-col">
          <span class="font-medium txt-medium text-ui-fg-base">
            Store
          </span>
          <span class="mb-4 text-ui-fg-muted txt-medium">
            Choose a store near you
          </span>
        </div>
        <div data-testid="delivery-options-container">
          <div class="pb-8 md:pt-0 pt-2">
            <button
              v-for="option in pickupMethods"
              :key="option.id"
              type="button"
              data-testid="delivery-option-radio"
              :disabled="option.insufficient_inventory"
              :class="[
                'flex items-center justify-between text-small-regular cursor-pointer py-4 border rounded-rounded px-8 mb-2 hover:shadow-borders-interactive-with-active w-full text-left',
                {
                  'border-ui-border-interactive': option.id === selectedId,
                  'hover:shadow-none cursor-not-allowed': option.insufficient_inventory
                }
              ]"
              @click="handleSetShippingMethod(option.id, 'pickup')"
            >
              <div class="flex items-start gap-x-4">
                <div
                  class="mt-0.5 size-4 rounded-full border-2 flex items-center justify-center"
                  :class="option.id === selectedId ? 'border-ui-fg-base' : 'border-gray-300'"
                >
                  <div
                    v-if="option.id === selectedId"
                    class="size-2 rounded-full bg-ui-fg-base"
                  />
                </div>
                <div class="flex flex-col">
                  <span class="text-base-regular">
                    {{ option.name }}
                  </span>
                  <span class="text-base-regular text-ui-fg-muted">
                    {{ formatAddress(option.service_zone?.fulfillment_set?.location?.address) }}
                  </span>
                </div>
              </div>
              <span class="justify-self-end text-ui-fg-base">
                {{ convertToLocale({ amount: option.amount ?? 0, currency_code: currencyCode }) }}
              </span>
            </button>
          </div>
        </div>
      </div>

      <div>
        <CheckoutErrorMessage
          :error="error"
          data-testid="delivery-option-error-message"
        />
        <UButton
          class="mt-6"
          size="lg"
          :disabled="!cart?.shipping_methods?.length"
          :loading="isLoading"
          data-testid="submit-delivery-option-button"
          @click="handleContinue"
        >
          Continue to payment
        </UButton>
      </div>
    </template>

    <div
      v-else
      class="text-small-regular"
    >
      <div
        v-if="cart && (cart.shipping_methods?.length ?? 0) > 0"
        class="flex flex-col w-1/3"
      >
        <p class="txt-medium-plus text-ui-fg-base mb-1">
          Method
        </p>
        <p class="txt-medium text-ui-fg-subtle">
          {{ cart.shipping_methods?.at(-1)?.name }}
          {{ convertToLocale({ amount: cart.shipping_methods?.at(-1)?.amount ?? 0, currency_code: cart.currency_code }) }}
        </p>
      </div>
    </div>

    <CommonDivider class="mt-8" />
  </div>
</template>

// storefront-vinext/src/modules/checkout/components/shipping/index.tsx
"use client"

import { RadioGroup, Radio } from "@headlessui/react"
import { setShippingMethod } from "@lib/data/cart"
import { calculatePriceForShippingOption } from "@lib/data/fulfillment"
import { convertToLocale } from "@lib/util/money"
import { CheckCircleSolid, Loader } from "@medusajs/icons"
import { HttpTypes } from "@medusajs/types"
import { Button, Heading, Text, clx } from "@medusajs/ui"
import ErrorMessage from "@modules/checkout/components/error-message"
import Divider from "@modules/common/components/divider"
import MedusaRadio from "@modules/common/components/radio"
import { usePathname, useRouter, useSearchParams } from "next/navigation"
import { useEffect, useMemo, useState } from "react"

const PICKUP_OPTION_ON = "__PICKUP_ON"
const PICKUP_OPTION_OFF = "__PICKUP_OFF"

type ShippingProps = {
  cart: HttpTypes.StoreCart
  availableShippingMethods:
    | (HttpTypes.StoreCartShippingOption & {
        service_zone?: {
          fulfillment_set?: {
            type?: string
            location?: {
              address?: {
                address_1?: string | null
                address_2?: string | null
                postal_code?: string | null
                city?: string | null
                country_code?: string | null
              } | null
            } | null
          } | null
        } | null
      })[]
    | null
  initialStep?: string
}

function formatAddress(address?: {
  address_1?: string | null
  address_2?: string | null
  postal_code?: string | null
  city?: string | null
  country_code?: string | null
} | null) {
  if (!address) {
    return ""
  }

  let ret = ""

  if (address.address_1) {
    ret += ` ${address.address_1}`
  }

  if (address.address_2) {
    ret += `, ${address.address_2}`
  }

  if (address.postal_code) {
    ret += `, ${address.postal_code} ${address.city}`
  }

  if (address.country_code) {
    ret += `, ${address.country_code.toUpperCase()}`
  }

  return ret
}

const Shipping: React.FC<ShippingProps> = ({
  cart,
  availableShippingMethods,
  initialStep,
}) => {
  const [isLoading, setIsLoading] = useState(false)
  const [isLoadingPrices, setIsLoadingPrices] = useState(true)

  const [showPickupOptions, setShowPickupOptions] =
    useState<string>(PICKUP_OPTION_OFF)
  const [calculatedPricesMap, setCalculatedPricesMap] = useState<
    Record<string, number>
  >({})
  const [error, setError] = useState<string | null>(null)
  const [shippingMethodId, setShippingMethodId] = useState<string | null>(
    cart.shipping_methods?.at(-1)?.shipping_option_id || null
  )

  const searchParams = useSearchParams()
  const router = useRouter()
  const pathname = usePathname()

  const step = searchParams.get("step") || initialStep || "address"
  const isOpen = step === "delivery"
  const shippingMethods = useMemo(
    () => availableShippingMethods ?? [],
    [availableShippingMethods]
  )
  const currentShippingMethod = cart.shipping_methods?.at(-1)

  const _shippingMethods = useMemo(
    () =>
      shippingMethods.filter(
        (sm) => sm.service_zone?.fulfillment_set?.type !== "pickup"
      ),
    [shippingMethods]
  )

  const _pickupMethods = useMemo(
    () =>
      shippingMethods.filter(
        (sm) => sm.service_zone?.fulfillment_set?.type === "pickup"
      ),
    [shippingMethods]
  )

  const hasPickupOptions = !!_pickupMethods?.length

  useEffect(() => {
    setIsLoadingPrices(true)

    if (_shippingMethods.length) {
      const promises = _shippingMethods
        .filter((sm) => sm.price_type === "calculated")
        .map((sm) => calculatePriceForShippingOption(sm.id, cart.id))

      if (promises.length) {
        Promise.allSettled(promises).then((res) => {
          const pricesMap: Record<string, number> = {}
          res.forEach((result) => {
            if (result.status === "fulfilled" && result.value?.id) {
              pricesMap[result.value.id] = result.value.amount
            }
          })

          setCalculatedPricesMap(pricesMap)
          setIsLoadingPrices(false)
        })
      } else {
        setIsLoadingPrices(false)
      }
    } else {
      setIsLoadingPrices(false)
    }

    if (_pickupMethods.find((m) => m.id === shippingMethodId)) {
      setShowPickupOptions(PICKUP_OPTION_ON)
    }
  }, [_pickupMethods, _shippingMethods, cart.id, shippingMethodId])

  const handleEdit = () => {
    router.push(pathname + "?step=delivery", { scroll: false })
  }

  const handleSubmit = () => {
    router.push(pathname + "?step=payment", { scroll: false })
  }

  const handleSetShippingMethod = async (
    id: string,
    variant: "shipping" | "pickup"
  ) => {
    setError(null)

    if (variant === "pickup") {
      setShowPickupOptions(PICKUP_OPTION_ON)
    } else {
      setShowPickupOptions(PICKUP_OPTION_OFF)
    }

    let currentId: string | null = null
    setIsLoading(true)
    setShippingMethodId((prev) => {
      currentId = prev
      return id
    })

    await setShippingMethod({ cartId: cart.id, shippingMethodId: id })
      .catch((err) => {
        setShippingMethodId(currentId)

        setError(err.message)
      })
      .finally(() => {
        setIsLoading(false)
      })
  }

  useEffect(() => {
    setError(null)
  }, [isOpen])

  return (
    <div className="bg-white">
      <div className="flex flex-row items-center justify-between mb-6">
        <Heading
          level="h2"
          className={clx(
            "flex flex-row text-3xl-regular gap-x-2 items-baseline",
            {
              "opacity-50 pointer-events-none select-none":
                !isOpen && cart.shipping_methods?.length === 0,
            }
          )}
        >
          Delivery
          {!isOpen && (cart.shipping_methods?.length ?? 0) > 0 && (
            <CheckCircleSolid />
          )}
        </Heading>
        {!isOpen &&
          cart?.shipping_address &&
          cart?.billing_address &&
          cart?.email && (
            <Text>
              <button
                onClick={handleEdit}
                className="text-ui-fg-interactive hover:text-ui-fg-interactive-hover"
                data-testid="edit-delivery-button"
              >
                Edit
              </button>
            </Text>
          )}
      </div>
      {isOpen ? (
        <>
          <div className="grid">
            <div className="flex flex-col">
              <span className="font-medium txt-medium text-ui-fg-base">
                Shipping method
              </span>
              <span className="mb-4 text-ui-fg-muted txt-medium">
                How would you like you order delivered
              </span>
            </div>
            <div data-testid="delivery-options-container">
              <div className="pb-8 md:pt-0 pt-2">
                {hasPickupOptions && (
                  <RadioGroup
                    value={showPickupOptions}
                    onChange={(value) => {
                      const id = _pickupMethods.find(
                        (option) => !option.insufficient_inventory
                      )?.id

                      if (id) {
                        handleSetShippingMethod(id, "pickup")
                      }
                    }}
                  >
                    <Radio
                      value={PICKUP_OPTION_ON}
                      data-testid="delivery-option-radio"
                      className={clx(
                        "flex items-center justify-between text-small-regular cursor-pointer py-4 border rounded-rounded px-8 mb-2 hover:shadow-borders-interactive-with-active",
                        {
                          "border-ui-border-interactive":
                            showPickupOptions === PICKUP_OPTION_ON,
                        }
                      )}
                    >
                      <div className="flex items-center gap-x-4">
                        <MedusaRadio
                          checked={showPickupOptions === PICKUP_OPTION_ON}
                        />
                        <span className="text-base-regular">
                          Pick up your order
                        </span>
                      </div>
                      <span className="justify-self-end text-ui-fg-base">
                        -
                      </span>
                    </Radio>
                  </RadioGroup>
                )}
                  <RadioGroup
                    value={shippingMethodId}
                    onChange={(value) => {
                      if (value) {
                        handleSetShippingMethod(value, "shipping")
                      }
                    }}
                  >
                  {_shippingMethods?.map((option) => {
                    const isDisabled =
                      option.price_type === "calculated" &&
                      !isLoadingPrices &&
                      typeof calculatedPricesMap[option.id] !== "number"

                    return (
                      <Radio
                        key={option.id}
                        value={option.id}
                        data-testid="delivery-option-radio"
                        disabled={isDisabled}
                        className={clx(
                          "flex items-center justify-between text-small-regular cursor-pointer py-4 border rounded-rounded px-8 mb-2 hover:shadow-borders-interactive-with-active",
                          {
                            "border-ui-border-interactive":
                              option.id === shippingMethodId,
                            "hover:shadow-brders-none cursor-not-allowed":
                              isDisabled,
                          }
                        )}
                      >
                        <div className="flex items-center gap-x-4">
                          <MedusaRadio
                            checked={option.id === shippingMethodId}
                          />
                          <span className="text-base-regular">
                            {option.name}
                          </span>
                        </div>
                        <span className="justify-self-end text-ui-fg-base">
                          {option.price_type === "flat" ? (
                            convertToLocale({
                              amount: option.amount!,
                              currency_code: cart?.currency_code,
                            })
                          ) : calculatedPricesMap[option.id] ? (
                            convertToLocale({
                              amount: calculatedPricesMap[option.id],
                              currency_code: cart?.currency_code,
                            })
                          ) : isLoadingPrices ? (
                            <Loader />
                          ) : (
                            "-"
                          )}
                        </span>
                      </Radio>
                    )
                  })}
                </RadioGroup>
              </div>
            </div>
          </div>

          {showPickupOptions === PICKUP_OPTION_ON && (
            <div className="grid">
              <div className="flex flex-col">
                <span className="font-medium txt-medium text-ui-fg-base">
                  Store
                </span>
                <span className="mb-4 text-ui-fg-muted txt-medium">
                  Choose a store near you
                </span>
              </div>
              <div data-testid="delivery-options-container">
                <div className="pb-8 md:pt-0 pt-2">
                  <RadioGroup
                    value={shippingMethodId}
                    onChange={(value) => {
                      if (value) {
                        handleSetShippingMethod(value, "pickup")
                      }
                    }}
                  >
                    {_pickupMethods?.map((option) => {
                      return (
                        <Radio
                          key={option.id}
                          value={option.id}
                          disabled={option.insufficient_inventory}
                          data-testid="delivery-option-radio"
                          className={clx(
                            "flex items-center justify-between text-small-regular cursor-pointer py-4 border rounded-rounded px-8 mb-2 hover:shadow-borders-interactive-with-active",
                            {
                              "border-ui-border-interactive":
                                option.id === shippingMethodId,
                              "hover:shadow-brders-none cursor-not-allowed":
                                option.insufficient_inventory,
                            }
                          )}
                        >
                          <div className="flex items-start gap-x-4">
                            <MedusaRadio
                              checked={option.id === shippingMethodId}
                            />
                            <div className="flex flex-col">
                              <span className="text-base-regular">
                                {option.name}
                              </span>
                              <span className="text-base-regular text-ui-fg-muted">
                                {formatAddress(
                                  option.service_zone?.fulfillment_set?.location
                                    ?.address
                                )}
                              </span>
                            </div>
                          </div>
                          <span className="justify-self-end text-ui-fg-base">
                            {convertToLocale({
                              amount: option.amount!,
                              currency_code: cart?.currency_code,
                            })}
                          </span>
                        </Radio>
                      )
                    })}
                  </RadioGroup>
                </div>
              </div>
            </div>
          )}

          <div>
            <ErrorMessage
              error={error}
              data-testid="delivery-option-error-message"
            />
            <Button
              size="large"
              className="mt"
              onClick={handleSubmit}
              isLoading={isLoading}
              disabled={!cart.shipping_methods?.[0]}
              data-testid="submit-delivery-option-button"
            >
              Continue to payment
            </Button>
          </div>
        </>
      ) : (
        <div>
          <div className="text-small-regular">
            {cart && (cart.shipping_methods?.length ?? 0) > 0 && (
              <div className="flex flex-col w-1/3">
                <Text className="txt-medium-plus text-ui-fg-base mb-1">
                  Method
                </Text>
                <Text className="txt-medium text-ui-fg-subtle">
                  {currentShippingMethod?.name}{" "}
                  {currentShippingMethod &&
                    convertToLocale({
                      amount: currentShippingMethod.amount,
                      currency_code: cart.currency_code,
                    })}
                </Text>
              </div>
            )}
          </div>
        </div>
      )}
      <Divider className="mt-8" />
    </div>
  )
}

export default Shipping
