// storefront-nuxt/app/components/product/Thumbnail.vue
<script setup lang="ts">
const props = withDefaults(defineProps<{
  thumbnail?: string | null
  images?: any[] | null
  size?: 'small' | 'medium' | 'large' | 'full' | 'square'
  isFeatured?: boolean
  dataTestid?: string
}>(), {
  size: 'small',
  isFeatured: false,
})

const initialImage = computed(() => props.thumbnail || props.images?.[0]?.url)

const aspectClass = computed(() => {
  if (props.size === 'square') return 'aspect-[11/14]'
  if (props.size === 'full') return 'aspect-[9/16]'
  if (props.isFeatured) return 'aspect-[11/14]'
  return 'aspect-[9/16]'
})

const sizeClasses = computed(() => {
  const classes: Record<string, boolean> = {
    'w-[180px]': props.size === 'small',
    'w-[290px]': props.size === 'medium',
    'w-[440px]': props.size === 'large',
    'w-full': props.size === 'full',
  }
  return [aspectClass.value, ...Object.entries(classes).filter(([, v]) => v).map(([k]) => k)].join(' ')
})
</script>

<template>
  <div
    :class="[
      'relative w-full overflow-hidden p-4 shadow-elevation-card-rest bg-ui-bg-subtle rounded-large group-hover:shadow-elevation-card-hover transition-shadow ease-in-out duration-150',
      sizeClasses
    ]"
    :data-testid="dataTestid"
  >
    <NuxtImg
      v-if="initialImage"
      :src="initialImage"
      alt="Thumbnail"
      class="absolute inset-0 object-cover object-center w-full h-full"
      :quality="50"
      loading="lazy"
      :draggable="false"
      sizes="(max-width: 576px) 280px, (max-width: 768px) 360px, (max-width: 992px) 480px, 800px"
    />
    <div v-else class="w-full h-full absolute inset-0 flex items-center justify-center">
      <UIcon name="i-lucide-image" class="w-8 h-8 text-ui-fg-muted" />
    </div>
  </div>
</template>

// storefront-next/src/modules/products/components/thumbnail/index.tsx
import { Container, clx } from "@medusajs/ui"
import Image from "next/image"
import React from "react"

import PlaceholderImage from "@modules/common/icons/placeholder-image"

type ThumbnailProps = {
  thumbnail?: string | null
  // TODO: Fix image typings
  images?: any[] | null
  size?: "small" | "medium" | "large" | "full" | "square"
  isFeatured?: boolean
  className?: string
  "data-testid"?: string
}

const Thumbnail: React.FC<ThumbnailProps> = ({
  thumbnail,
  images,
  size = "small",
  isFeatured,
  className,
  "data-testid": dataTestid,
}) => {
  const initialImage = thumbnail || images?.[0]?.url

  return (
    <Container
      className={clx(
        "relative w-full overflow-hidden p-4 bg-ui-bg-subtle shadow-elevation-card-rest rounded-large group-hover:shadow-elevation-card-hover transition-shadow ease-in-out duration-150",
        className,
        {
          "aspect-11/14": isFeatured,
          "aspect-9/16": !isFeatured && size !== "square",
          "aspect-square": size === "square",
          "w-[180px]": size === "small",
          "w-[290px]": size === "medium",
          "w-[440px]": size === "large",
          "w-full": size === "full",
        }
      )}
      data-testid={dataTestid}
    >
      <ImageOrPlaceholder image={initialImage} size={size} />
    </Container>
  )
}

const ImageOrPlaceholder = ({
  image,
  size,
}: Pick<ThumbnailProps, "size"> & { image?: string }) => {
  return image ? (
    <Image
      src={image}
      alt="Thumbnail"
      className="absolute inset-0 object-cover object-center"
      quality={50}
      sizes="(max-width: 576px) 280px, (max-width: 768px) 360px, (max-width: 992px) 480px, 800px"
      fill
    />
  ) : (
    <div className="w-full h-full absolute inset-0 flex items-center justify-center">
      <PlaceholderImage size={size === "small" ? 16 : 24} />
    </div>
  )
}

export default Thumbnail
