// storefront-vinext/src/modules/products/components/image-gallery/index.tsx
import { HttpTypes } from "@medusajs/types"
import { Container } from "@medusajs/ui"
import Image from "next/image"

type ImageGalleryProps = {
  images: HttpTypes.StoreProductImage[]
}

const ImageGallery = ({ images }: ImageGalleryProps) => {
  return (
    <div className="flex items-start relative">
      <div className="flex flex-col flex-1 small:mx-16 gap-y-4">
        {images.map((image, index) => {
          return (
            <Container
              key={image.id}
              className="relative aspect-29/34 w-full overflow-hidden bg-ui-bg-subtle"
              id={image.id}
            >
              {!!image.url && (
                <Image
                  src={image.url}
                  priority={index <= 2 ? true : false}
                  className="absolute inset-0 h-full w-full rounded-rounded"
                  alt={`Product image ${index + 1}`}
                  fill
                  sizes="(max-width: 576px) 280px, (max-width: 768px) 360px, (max-width: 992px) 480px, 800px"
                  style={{
                    objectFit: "cover",
                  }}
                />
              )}
            </Container>
          )
        })}
      </div>
    </div>
  )
}

export default ImageGallery

// storefront-nuxt/app/components/product/ImageGallery.vue
<script setup lang="ts">
defineProps<{
  images: any[]
}>()
</script>

<template>
  <div class="flex items-start relative">
    <div class="flex flex-col flex-1 small:mx-16 gap-y-4">
      <div
        v-for="(image, index) in images"
        :key="image.id"
        class="relative aspect-[29/34] w-full overflow-hidden bg-ui-bg-subtle rounded-rounded"
        :id="image.id"
      >
        <NuxtImg
          v-if="image.url"
          :src="image.url"
          :alt="`Product image ${index + 1}`"
          class="absolute inset-0 rounded-rounded object-cover w-full h-full"
          :loading="index <= 2 ? 'eager' : 'lazy'"
          sizes="(max-width: 576px) 280px, (max-width: 768px) 360px, (max-width: 992px) 480px, 800px"
        />
      </div>
    </div>
  </div>
</template>
