// storefront-vinext/src/app/[countryCode]/(main)/account/@dashboard/orders/page.tsx
import { Metadata } from "next"

import OrderOverview from "@modules/account/components/order-overview"
import { notFound } from "next/navigation"
import { listOrders } from "@lib/data/orders"
import Divider from "@modules/common/components/divider"
import TransferRequestForm from "@modules/account/components/transfer-request-form"

export const metadata: Metadata = {
  title: "Orders",
  description: "Overview of your previous orders.",
}

export default async function Orders(props: {
  params: Promise<{ countryCode: string }>
}) {
  const params = await props.params
  const orders = await listOrders()

  if (!orders) {
    notFound()
  }

  return (
    <div className="w-full" data-testid="orders-page-wrapper">
      <div className="mb-8 flex flex-col gap-y-4">
        <h1 className="text-2xl-semi">Orders</h1>
        <p className="text-base-regular">
          View your previous orders and their status. You can also create
          returns or exchanges for your orders if needed.
        </p>
      </div>
      <div>
        <OrderOverview orders={orders} countryCode={params.countryCode} />
        <Divider className="my-16" />
        <TransferRequestForm />
      </div>
    </div>
  )
}

// storefront-nuxt/app/pages/[countryCode]/account/orders/index.vue
<script setup lang="ts">
useSeoMeta({
  title: 'Orders | Medusa Store',
  description: 'Overview of your previous orders.',
})

const { data: orders } = await useAsyncData('my-orders', () =>
  $fetch('/api/orders')
)
</script>

<template>
  <div class="w-full" data-testid="orders-page-wrapper">
    <div class="mb-8 flex flex-col gap-y-4">
      <h1 class="text-2xl-semi">Orders</h1>
      <p class="text-base-regular">
        View your previous orders and their status. You can also create returns or exchanges for your orders if needed.
      </p>
    </div>
    <div>
      <AccountOrderOverview :orders="(orders as any)?.orders ?? []" />
      <div class="w-full h-px bg-gray-200 my-16" />
      <AccountTransferRequestForm />
    </div>
  </div>
</template>
