// storefront-nuxt/app/components/account/TransferRequestForm.vue
<script setup lang="ts">
const orderId = ref('')
const loading = ref(false)
const error = ref<string | null>(null)
const showSuccess = ref(false)
const successOrder = ref<{ id: string, email: string } | null>(null)

async function handleSubmit() {
  if (!orderId.value.trim()) return

  loading.value = true
  error.value = null
  showSuccess.value = false

  try {
    const result = await $fetch('/api/orders/transfer', {
      method: 'POST',
      body: { order_id: orderId.value },
    })
    successOrder.value = result as any
    showSuccess.value = true
    orderId.value = ''
  } catch (e: any) {
    error.value = e?.data?.message || e?.message || 'An error occurred'
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <div class="flex flex-col gap-y-4 w-full">
    <div class="grid small:grid-cols-2 items-center gap-x-8 gap-y-4 w-full">
      <div class="flex flex-col gap-y-1">
        <h3 class="text-lg text-neutral-950 font-semibold">
          Order transfers
        </h3>
        <p class="text-base-regular text-neutral-500">
          Can't find the order you are looking for?
          <br> Connect an order to your account.
        </p>
      </div>
      <form
        class="flex flex-col gap-y-1 small:items-end"
        @submit.prevent="handleSubmit"
      >
        <div class="flex flex-col gap-y-2 w-full">
          <UInput
            v-model="orderId"
            class="w-full"
            placeholder="Order ID"
            size="lg"
          />
          <UButton
            type="submit"
            variant="outline"
            class="w-fit whitespace-nowrap self-end"
            :loading="loading"
          >
            Request transfer
          </UButton>
        </div>
      </form>
    </div>

    <p
      v-if="error"
      class="text-base-regular text-rose-500 text-right"
    >
      {{ error }}
    </p>

    <div
      v-if="showSuccess && successOrder"
      class="flex justify-between p-4 bg-neutral-50 shadow-borders-base w-full self-stretch items-center"
    >
      <div class="flex gap-x-2 items-center">
        <UIcon
          name="i-lucide-check-circle"
          class="w-4 h-4 text-emerald-500"
        />
        <div class="flex flex-col gap-y-1">
          <p class="text-medium-pl text-neutral-950">
            Transfer for order {{ successOrder.id }} requested
          </p>
          <p class="text-base-regular text-neutral-600">
            Transfer request email sent to {{ successOrder.email }}
          </p>
        </div>
      </div>
      <button
        class="h-fit p-1 hover:bg-neutral-100 rounded"
        @click="showSuccess = false"
      >
        <UIcon
          name="i-lucide-x-circle"
          class="w-4 h-4 text-neutral-500"
        />
      </button>
    </div>
  </div>
</template>

// storefront-vinext/src/modules/account/components/transfer-request-form/index.tsx
"use client"

import { useActionState } from "react"
import { createTransferRequest } from "@lib/data/orders"
import { Text, Heading, Input, Button, IconButton, Toaster } from "@medusajs/ui"
import { SubmitButton } from "@modules/checkout/components/submit-button"
import { CheckCircleMiniSolid, XCircleSolid } from "@medusajs/icons"
import { useEffect, useState } from "react"

export default function TransferRequestForm() {
  const [showSuccess, setShowSuccess] = useState(false)

  const [state, formAction] = useActionState(createTransferRequest, {
    success: false,
    error: null,
    order: null,
  })

  useEffect(() => {
    if (state.success && state.order) {
      setShowSuccess(true)
    }
  }, [state.success, state.order])

  return (
    <div className="flex flex-col gap-y-4 w-full">
      <div className="grid sm:grid-cols-2 items-center gap-x-8 gap-y-4 w-full">
        <div className="flex flex-col gap-y-1">
          <Heading level="h3" className="text-lg text-ui-fg-base">
            Order transfers
          </Heading>
          <Text className="text-base-regular text-ui-fg-subtle">
            Can&apos;t find the order you are looking for?
            <br /> Connect an order to your account.
          </Text>
        </div>
        <form
          action={formAction}
          className="flex flex-col gap-y-1 sm:items-end"
        >
          <div className="flex flex-col gap-y-2 w-full">
            <Input className="w-full" name="order_id" placeholder="Order ID" />
            <SubmitButton
              variant="secondary"
              className="w-fit whitespace-nowrap self-end"
            >
              Request transfer
            </SubmitButton>
          </div>
        </form>
      </div>
      {!state.success && state.error && (
        <Text className="text-base-regular text-ui-fg-error text-right">
          {state.error}
        </Text>
      )}
      {showSuccess && (
        <div className="flex justify-between p-4 bg-ui-bg-subtle shadow-borders-base w-full self-stretch items-center">
          <div className="flex gap-x-2 items-center">
            <CheckCircleMiniSolid className="w-4 h-4 text-ui-fg-interactive" />
            <div className="flex flex-col gap-y-1">
              <Text className="text-medim-pl text-ui-fg-base">
                Transfer for order {state.order?.id} requested
              </Text>
              <Text className="text-base-regular text-ui-fg-subtle">
                Transfer request email sent to {state.order?.email}
              </Text>
            </div>
          </div>
          <IconButton
            variant="transparent"
            className="h-fit"
            onClick={() => setShowSuccess(false)}
          >
            <XCircleSolid className="w-4 h-4 text-ui-fg-subtle" />
          </IconButton>
        </div>
      )}
    </div>
  )
}
