// storefront-nuxt/app/components/account/AccountNav.vue
<script setup lang="ts">
const { customer, logout } = useCustomer()
const route = useRoute()
const countryCode = useCountryCode()

const isOnAccountRoot = computed(() => {
  return route.path === `/${countryCode.value}/account` || route.path === `/${countryCode.value}/account/`
})

interface NavItem {
  label: string
  to: string
  icon: string
}

const navItems: NavItem[] = [
  { label: 'Profile', to: '/account', icon: 'lucide:user' },
  { label: 'Addresses', to: '/account/addresses', icon: 'lucide:map-pin' },
  { label: 'Orders', to: '/account/orders', icon: 'lucide:shopping-bag' }
]

function isActive(itemTo: string) {
  const fullPath = `/${countryCode.value}${itemTo}`
  if (itemTo === '/account') {
    return route.path === fullPath || route.path === `${fullPath}/`
  }
  return route.path.startsWith(fullPath)
}

async function handleLogout() {
  await logout(countryCode.value)
}
</script>

<template>
  <div>
    <!-- Mobile -->
    <div class="small:hidden">
      <div v-if="!isOnAccountRoot">
        <NuxtLink
          :to="`/${countryCode}/account`"
          class="flex items-center gap-x-2 text-small-regular py-2"
        >
          <UIcon
            name="lucide:chevron-left"
            class="size-4"
          />
          <span>Account</span>
        </NuxtLink>
      </div>
      <div v-else>
        <div class="text-xl-semi mb-4 px-8">
          Hello {{ customer?.first_name || 'there' }}
        </div>
        <div class="text-base-regular">
          <ul>
            <li
              v-for="item in navItems"
              :key="item.to"
            >
              <NuxtLink
                :to="`/${countryCode}${item.to}`"
                class="flex items-center justify-between border-b border-gray-200 py-4 px-8"
              >
                <div class="flex items-center gap-x-2">
                  <UIcon
                    :name="item.icon"
                    class="size-5"
                  />
                  <span>{{ item.label }}</span>
                </div>
                <UIcon
                  name="lucide:chevron-right"
                  class="size-4"
                />
              </NuxtLink>
            </li>
            <li>
              <button
                class="flex items-center justify-between border-b border-gray-200 py-4 px-8 w-full"
                @click="handleLogout"
              >
                <div class="flex items-center gap-x-2">
                  <UIcon
                    name="lucide:log-out"
                    class="size-5"
                  />
                  <span>Log out</span>
                </div>
                <UIcon
                  name="lucide:chevron-right"
                  class="size-4"
                />
              </button>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <!-- Desktop -->
    <div class="hidden small:block" data-testid="account-nav">
      <div>
        <div class="pb-4">
          <h3 class="text-base-semi">Account</h3>
        </div>
        <div class="text-base-regular">
          <ul class="flex mb-0 justify-start items-start flex-col gap-y-4">
            <li>
              <NuxtLink
                :to="`/${countryCode}/account`"
                class="hover:text-ui-fg-base"
                :class="isActive('/account') ? 'text-ui-fg-base font-semibold' : 'text-ui-fg-subtle'"
                data-testid="overview-link"
              >
                Overview
              </NuxtLink>
            </li>
            <li>
              <NuxtLink
                :to="`/${countryCode}/account/profile`"
                class="hover:text-ui-fg-base"
                :class="isActive('/account/profile') ? 'text-ui-fg-base font-semibold' : 'text-ui-fg-subtle'"
                data-testid="profile-link"
              >
                Profile
              </NuxtLink>
            </li>
            <li>
              <NuxtLink
                :to="`/${countryCode}/account/addresses`"
                class="hover:text-ui-fg-base"
                :class="isActive('/account/addresses') ? 'text-ui-fg-base font-semibold' : 'text-ui-fg-subtle'"
                data-testid="addresses-link"
              >
                Addresses
              </NuxtLink>
            </li>
            <li>
              <NuxtLink
                :to="`/${countryCode}/account/orders`"
                class="hover:text-ui-fg-base"
                :class="isActive('/account/orders') ? 'text-ui-fg-base font-semibold' : 'text-ui-fg-subtle'"
                data-testid="orders-link"
              >
                Orders
              </NuxtLink>
            </li>
            <li class="text-grey-700">
              <button
                type="button"
                data-testid="logout-button"
                @click="handleLogout"
              >
                Log out
              </button>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</template>

// storefront-vinext/src/modules/account/components/account-nav/index.tsx
"use client"

import { clx } from "@medusajs/ui"
import { ArrowRightOnRectangle } from "@medusajs/icons"
import { useParams, usePathname } from "next/navigation"

import ChevronDown from "@modules/common/icons/chevron-down"
import User from "@modules/common/icons/user"
import MapPin from "@modules/common/icons/map-pin"
import Package from "@modules/common/icons/package"
import LocalizedClientLink from "@modules/common/components/localized-client-link"
import { HttpTypes } from "@medusajs/types"
import { signout } from "@lib/data/customer"

const AccountNav = ({
  customer,
}: {
  customer: HttpTypes.StoreCustomer | null
}) => {
  const pathname = usePathname()
  const browserRoute =
    typeof window !== "undefined" ? window.location.pathname : ""
  const route = pathname && pathname !== "/" ? pathname : browserRoute
  const params = useParams()
  const countryCode =
    typeof params?.countryCode === "string"
      ? params.countryCode
      : route?.split("/").filter(Boolean)[0] || ""

  const handleLogout = async () => {
    await signout(countryCode)
  }

  return (
    <div>
      <div className="small:hidden" data-testid="mobile-account-nav">
        {route !== `/${countryCode}/account` ? (
          <LocalizedClientLink
            href="/account"
            className="flex items-center gap-x-2 text-small-regular py-2"
            data-testid="account-main-link"
          >
            <>
              <ChevronDown className="transform rotate-90" />
              <span>Account</span>
            </>
          </LocalizedClientLink>
        ) : (
          <>
            <div className="text-xl-semi mb-4 px-8">
              Hello {customer?.first_name}
            </div>
            <div className="text-base-regular">
              <ul>
                <li>
                  <LocalizedClientLink
                    href="/account/profile"
                    className="flex items-center justify-between py-4 border-b border-gray-200 px-8"
                    data-testid="profile-link"
                  >
                    <>
                      <div className="flex items-center gap-x-2">
                        <User size={20} />
                        <span>Profile</span>
                      </div>
                      <ChevronDown className="transform -rotate-90" />
                    </>
                  </LocalizedClientLink>
                </li>
                <li>
                  <LocalizedClientLink
                    href="/account/addresses"
                    className="flex items-center justify-between py-4 border-b border-gray-200 px-8"
                    data-testid="addresses-link"
                  >
                    <>
                      <div className="flex items-center gap-x-2">
                        <MapPin size={20} />
                        <span>Addresses</span>
                      </div>
                      <ChevronDown className="transform -rotate-90" />
                    </>
                  </LocalizedClientLink>
                </li>
                <li>
                  <LocalizedClientLink
                    href="/account/orders"
                    className="flex items-center justify-between py-4 border-b border-gray-200 px-8"
                    data-testid="orders-link"
                  >
                    <div className="flex items-center gap-x-2">
                      <Package size={20} />
                      <span>Orders</span>
                    </div>
                    <ChevronDown className="transform -rotate-90" />
                  </LocalizedClientLink>
                </li>
                <li>
                  <button
                    type="button"
                    className="flex items-center justify-between py-4 border-b border-gray-200 px-8 w-full"
                    onClick={handleLogout}
                    data-testid="logout-button"
                  >
                    <div className="flex items-center gap-x-2">
                      <ArrowRightOnRectangle />
                      <span>Log out</span>
                    </div>
                    <ChevronDown className="transform -rotate-90" />
                  </button>
                </li>
              </ul>
            </div>
          </>
        )}
      </div>
      <div className="hidden small:block" data-testid="account-nav">
        <div>
          <div className="pb-4">
            <h3 className="text-base-semi">Account</h3>
          </div>
          <div className="text-base-regular">
            <ul className="flex mb-0 justify-start items-start flex-col gap-y-4">
              <li>
                <AccountNavLink
                  href="/account"
                  route={route!}
                  data-testid="overview-link"
                >
                  Overview
                </AccountNavLink>
              </li>
              <li>
                <AccountNavLink
                  href="/account/profile"
                  route={route!}
                  data-testid="profile-link"
                >
                  Profile
                </AccountNavLink>
              </li>
              <li>
                <AccountNavLink
                  href="/account/addresses"
                  route={route!}
                  data-testid="addresses-link"
                >
                  Addresses
                </AccountNavLink>
              </li>
              <li>
                <AccountNavLink
                  href="/account/orders"
                  route={route!}
                  data-testid="orders-link"
                >
                  Orders
                </AccountNavLink>
              </li>
              <li className="text-grey-700">
                <button
                  type="button"
                  onClick={handleLogout}
                  data-testid="logout-button"
                >
                  Log out
                </button>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  )
}

type AccountNavLinkProps = {
  href: string
  route: string
  children: React.ReactNode
  "data-testid"?: string
}

const AccountNavLink = ({
  href,
  route,
  children,
  "data-testid": dataTestId,
}: AccountNavLinkProps) => {
  const params = useParams()
  const countryCode =
    typeof params?.countryCode === "string"
      ? params.countryCode
      : route.split("/").filter(Boolean)[0] || ""

  const active = route.split(countryCode)[1] === href
  return (
    <LocalizedClientLink
      href={href}
      className={clx("text-ui-fg-subtle hover:text-ui-fg-base", {
        "text-ui-fg-base font-semibold": active,
      })}
      data-testid={dataTestId}
    >
      {children}
    </LocalizedClientLink>
  )
}

export default AccountNav
