// storefront-vinext/src/app/[countryCode]/(main)/order/[id]/transfer/[token]/decline/page.tsx
import { declineTransferRequest } from "@lib/data/orders"
import { Heading, Text } from "@medusajs/ui"
import TransferImage from "@modules/order/components/transfer-image"

export default async function TransferPage({
  params,
}: {
  params: { id: string; token: string }
}) {
  const { id, token } = params

  const { success, error } = await declineTransferRequest(id, token)

  return (
    <div className="flex flex-col gap-y-4 items-start w-2/5 mx-auto mt-10 mb-20">
      <TransferImage />
      <div className="flex flex-col gap-y-6">
        {success && (
          <>
            <Heading level="h1" className="text-xl text-ui-fg-base">
              Order transfer declined!
            </Heading>
            <Text className="text-ui-fg-subtle">
              Transfer of order {id} has been successfully declined.
            </Text>
          </>
        )}
        {!success && (
          <>
            <Text className="text-ui-fg-subtle">
              There was an error declining the transfer. Please try again.
            </Text>
            {error && (
              <Text className="text-ui-fg-error">Error message: {error}</Text>
            )}
          </>
        )}
      </div>
    </div>
  )
}

// storefront-nuxt/app/pages/[countryCode]/order/[id]/transfer/[token]/decline.vue
<script setup lang="ts">
const route = useRoute()
const orderId = computed(() => route.params.id as string)
const token = computed(() => route.params.token as string)

const result = ref<{ success: boolean; error?: string }>({ success: false })

onMounted(async () => {
  try {
    await $fetch('/api/orders', {
      method: 'POST',
      body: { action: 'decline-transfer', orderId: orderId.value, token: token.value },
    })
    result.value = { success: true }
  } catch (e: any) {
    result.value = { success: false, error: e.message || 'Unknown error' }
  }
})
</script>

<template>
  <div class="flex flex-col gap-y-4 items-start w-2/5 mx-auto mt-10 mb-20">
    <OrderTransferImage />
    <div class="flex flex-col gap-y-6">
      <template v-if="result.success">
        <h1 class="text-xl text-zinc-900">Order transfer declined!</h1>
        <p class="text-zinc-600">Transfer of order {{ orderId }} has been successfully declined.</p>
      </template>
      <template v-else>
        <p class="text-zinc-600">There was an error declining the transfer. Please try again.</p>
        <p v-if="result.error" class="text-red-500">Error message: {{ result.error }}</p>
      </template>
    </div>
  </div>
</template>
