// storefront-nuxt/app/components/account/OrderCard.vue
<script setup lang="ts">
import type { HttpTypes } from '@medusajs/types'
import { convertToLocale } from '~/utils/money'

const props = defineProps<{
  order: HttpTypes.StoreOrder
}>()

const countryCode = useCountryCode()

const numberOfLines = computed(() =>
  props.order.items?.reduce((sum, item) => sum + item.quantity, 0) ?? 0
)

const numberOfProducts = computed(() =>
  props.order.items?.length ?? 0
)

const firstThreeItems = computed(() =>
  (props.order.items ?? []).slice(0, 3)
)

function formatDate(date: string | Date) {
  return new Date(date).toDateString()
}
</script>

<template>
  <div
    class="bg-white flex flex-col"
    data-testid="order-card"
  >
    <div class="uppercase text-large-semi mb-1">
      #
      <span data-testid="order-display-id">
        {{ order.display_id }}
      </span>
    </div>
    <div class="flex items-center divide-x divide-gray-200 text-small-regular text-ui-fg-base">
      <span
        class="pr-2"
        data-testid="order-created-at"
      >
        {{ formatDate(order.created_at) }}
      </span>
      <span
        class="px-2"
        data-testid="order-amount"
      >
        {{ convertToLocale({ amount: order.total, currency_code: order.currency_code }) }}
      </span>
      <span class="pl-2">
        {{ numberOfLines }} {{ numberOfLines > 1 ? 'items' : 'item' }}
      </span>
    </div>
    <div class="grid grid-cols-2 small:grid-cols-4 gap-4 my-4">
      <div
        v-for="item in firstThreeItems"
        :key="item.id"
        class="flex flex-col gap-y-2"
        data-testid="order-item"
      >
        <ProductThumbnail
          :thumbnail="item.thumbnail"
          :images="[]"
          size="full"
        />
        <div class="flex items-center text-small-regular text-ui-fg-base">
          <span
            class="text-ui-fg-base font-semibold"
            data-testid="item-title"
          >
            {{ item.title }}
          </span>
          <span class="ml-2">x</span>
          <span data-testid="item-quantity">{{ item.quantity }}</span>
        </div>
      </div>
      <div
        v-if="numberOfProducts > 4"
        class="w-full h-full flex flex-col items-center justify-center"
      >
        <span class="text-small-regular text-ui-fg-base">
          + {{ numberOfLines - 4 }}
        </span>
        <span class="text-small-regular text-ui-fg-base">more</span>
      </div>
    </div>
    <div class="flex justify-end">
      <NuxtLink
        :to="`/${countryCode}/account/orders/details/${order.id}`"
      >
        <UButton
          data-testid="order-details-link"
          variant="outline"
        >
          See details
        </UButton>
      </NuxtLink>
    </div>
  </div>
</template>

// storefront-vinext/src/modules/account/components/order-card/index.tsx
import { Button } from "@medusajs/ui"
import { useMemo } from "react"

import Thumbnail from "@modules/products/components/thumbnail"
import LocalizedClientLink from "@modules/common/components/localized-client-link"
import { convertToLocale } from "@lib/util/money"
import { HttpTypes } from "@medusajs/types"

type OrderCardProps = {
  order: HttpTypes.StoreOrder
  countryCode: string
}

const OrderCard = ({ order, countryCode }: OrderCardProps) => {
  const numberOfLines = useMemo(() => {
    return (
      order.items?.reduce((acc, item) => {
        return acc + item.quantity
      }, 0) ?? 0
    )
  }, [order])

  const numberOfProducts = useMemo(() => {
    return order.items?.length ?? 0
  }, [order])

  return (
    <div className="bg-ui-bg-base flex flex-col" data-testid="order-card">
      <div className="uppercase text-large-semi mb-1">
        #<span data-testid="order-display-id">{order.display_id}</span>
      </div>
      <div className="flex items-center divide-x divide-ui-border-base text-small-regular text-ui-fg-base">
        <span className="pr-2" data-testid="order-created-at">
          {new Date(order.created_at).toDateString()}
        </span>
        <span className="px-2" data-testid="order-amount">
          {convertToLocale({
            amount: order.total,
            currency_code: order.currency_code,
          })}
        </span>
        <span className="pl-2">{`${numberOfLines} ${
          numberOfLines > 1 ? "items" : "item"
        }`}</span>
      </div>
      <div className="grid grid-cols-2 small:grid-cols-4 gap-4 my-4">
        {order.items?.slice(0, 3).map((i) => {
          return (
            <div
              key={i.id}
              className="flex flex-col gap-y-2"
              data-testid="order-item"
            >
              <Thumbnail thumbnail={i.thumbnail} images={[]} size="full" />
              <div className="flex items-center text-small-regular text-ui-fg-base">
                <span
                  className="text-ui-fg-base font-semibold"
                  data-testid="item-title"
                >
                  {i.title}
                </span>
                <span className="ml-2">x</span>
                <span data-testid="item-quantity">{i.quantity}</span>
              </div>
            </div>
          )
        })}
        {numberOfProducts > 4 && (
          <div className="w-full h-full flex flex-col items-center justify-center">
            <span className="text-small-regular text-ui-fg-base">
              + {numberOfLines - 4}
            </span>
            <span className="text-small-regular text-ui-fg-base">more</span>
          </div>
        )}
      </div>
      <div className="flex justify-end">
        <LocalizedClientLink
          href={`/account/orders/details/${order.id}`}
          countryCode={countryCode}
        >
          <Button data-testid="order-details-link" variant="secondary">
            See details
          </Button>
        </LocalizedClientLink>
      </div>
    </div>
  )
}

export default OrderCard
