// storefront-nuxt/app/components/product/MobileActions.vue
<script setup lang="ts">
import type { HttpTypes } from '@medusajs/types'
import { getProductPrice } from '~/utils/get-product-price'
import { isSimpleProduct } from '~/utils/product'

const props = defineProps<{
  product: HttpTypes.StoreProduct
  variant?: HttpTypes.StoreProductVariant
  options: Record<string, string | undefined>
  inStock?: boolean
  isAdding?: boolean
  show: boolean
  optionsDisabled: boolean
}>()

const emit = defineEmits<{
  (e: 'updateOptions', optionId: string, value: string): void
  (e: 'addToCart'): void
}>()

const isModalOpen = ref(false)

const price = computed(() => {
  return getProductPrice({
    product: props.product,
    variantId: props.variant?.id
  })
})

const selectedPrice = computed(() => {
  if (!price.value) return null
  return price.value.variantPrice || price.value.cheapestPrice || null
})

const isSimple = computed(() => isSimpleProduct(props.product))
</script>

<template>
  <div>
    <!-- Fixed bottom bar -->
    <div :class="['lg:hidden inset-x-0 bottom-0 fixed', !show ? 'pointer-events-none' : '']">
      <Transition
        enter-active-class="ease-in-out duration-300"
        enter-from-class="opacity-0"
        enter-to-class="opacity-100"
        leave-active-class="ease-in duration-300"
        leave-from-class="opacity-100"
        leave-to-class="opacity-0"
      >
        <div
          v-if="show"
          class="bg-white flex flex-col gap-y-3 justify-center items-center text-large-regular p-4 h-full w-full border-t border-gray-200"
          data-testid="mobile-actions"
        >
          <div class="flex items-center gap-x-2">
            <span data-testid="mobile-title">{{ product.title }}</span>
            <span>—</span>
            <div
              v-if="selectedPrice"
              class="flex items-end gap-x-2 text-ui-fg-base"
            >
              <p v-if="selectedPrice.price_type === 'sale'">
                <span class="line-through text-small-regular">{{ selectedPrice.original_price }}</span>
              </p>
              <span
                :class="selectedPrice.price_type === 'sale' ? 'text-ui-fg-interactive' : ''"
              >
                {{ selectedPrice.calculated_price }}
              </span>
            </div>
          </div>
          <div :class="['grid w-full gap-x-4', isSimple ? 'grid-cols-1' : 'grid-cols-2']">
            <UButton
              v-if="!isSimple"
              variant="outline"
              block
              data-testid="mobile-actions-button"
              @click="isModalOpen = true"
            >
              <div class="flex items-center justify-between w-full">
                <span>{{ variant ? Object.values(options).join(' / ') : 'Select Options' }}</span>
                <UIcon
                  name="i-lucide-chevron-down"
                  class="w-4 h-4"
                />
              </div>
            </UButton>
            <UButton
              block
              :disabled="!inStock || !variant"
              :loading="isAdding"
              data-testid="mobile-cart-button"
              @click="emit('addToCart')"
            >
              {{ !variant ? 'Select variant' : !inStock ? 'Out of stock' : 'Add to cart' }}
            </UButton>
          </div>
        </div>
      </Transition>
    </div>

    <!-- Options modal -->
    <ClientOnly>
      <UModal v-model:open="isModalOpen">
        <template #content>
          <div
            class="flex min-h-full h-full items-center justify-center text-center"
            data-testid="mobile-actions-modal"
          >
            <div class="w-full h-full transform overflow-hidden text-left flex flex-col gap-y-3">
              <div class="w-full flex justify-end pr-6 pt-6">
                <button
                  type="button"
                  class="bg-white w-12 h-12 rounded-full text-ui-fg-base flex justify-center items-center"
                  data-testid="close-modal-button"
                  @click="isModalOpen = false"
                >
                  <UIcon
                    name="i-lucide-x"
                    class="w-5 h-5"
                  />
                </button>
              </div>
              <div class="bg-white px-6 py-12 w-full">
                <div
                  v-if="(product.variants?.length ?? 0) > 1"
                  class="flex flex-col gap-y-6"
                >
                  <div
                    v-for="option in (product.options || [])"
                    :key="option.id"
                  >
                    <ProductOptionSelect
                      :option="option"
                      :current="options[option.id]"
                      :title="option.title ?? ''"
                      :disabled="optionsDisabled"
                      @update="(optId, val) => emit('updateOptions', optId, val)"
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </template>
      </UModal>
    </ClientOnly>
  </div>
</template>

// storefront-vinext/src/modules/products/components/product-actions/mobile-actions.tsx
import { Dialog, Transition } from "@headlessui/react"
import { Button, clx } from "@medusajs/ui"
import React, { Fragment, useMemo } from "react"

import useToggleState from "@lib/hooks/use-toggle-state"
import ChevronDown from "@modules/common/icons/chevron-down"
import X from "@modules/common/icons/x"

import { getProductPrice } from "@lib/util/get-product-price"
import OptionSelect from "./option-select"
import { HttpTypes } from "@medusajs/types"
import { isSimpleProduct } from "@lib/util/product"

type MobileActionsProps = {
  product: HttpTypes.StoreProduct
  variant?: HttpTypes.StoreProductVariant
  options: Record<string, string | undefined>
  updateOptions: (title: string, value: string) => void
  inStock?: boolean
  handleAddToCart: () => void
  isAdding?: boolean
  show: boolean
  optionsDisabled: boolean
}

const MobileActions: React.FC<MobileActionsProps> = ({
  product,
  variant,
  options,
  updateOptions,
  inStock,
  handleAddToCart,
  isAdding,
  show,
  optionsDisabled,
}) => {
  const { state, open, close } = useToggleState()

  const price = getProductPrice({
    product: product,
    variantId: variant?.id,
  })

  const selectedPrice = useMemo(() => {
    if (!price) {
      return null
    }
    const { variantPrice, cheapestPrice } = price

    return variantPrice || cheapestPrice || null
  }, [price])

  const isSimple = isSimpleProduct(product)

  return (
    <>
      <div
        className={clx("lg:hidden inset-x-0 bottom-0 fixed", {
          "pointer-events-none": !show,
        })}
      >
        <Transition
          as={Fragment}
          show={show}
          enter="ease-in-out duration-300"
          enterFrom="opacity-0"
          enterTo="opacity-100"
          leave="ease-in duration-300"
          leaveFrom="opacity-100"
          leaveTo="opacity-0"
        >
          <div className="bg-ui-bg-base flex flex-col gap-y-3 justify-center items-center text-large-regular p-4 h-full w-full border-t border-ui-border-base" data-testid="mobile-actions">
            <div className="flex items-center gap-x-2">
              <span data-testid="mobile-title">{product.title}</span>
              <span>—</span>
              {selectedPrice ? (
                <div className="flex items-end gap-x-2 text-ui-fg-base">
                  {selectedPrice.price_type === "sale" && (
                    <p>
                      <span className="line-through text-small-regular">
                        {selectedPrice.original_price}
                      </span>
                    </p>
                  )}
                  <span
                    className={clx({
                      "text-ui-fg-interactive":
                        selectedPrice.price_type === "sale",
                    })}
                  >
                    {selectedPrice.calculated_price}
                  </span>
                </div>
              ) : (
                <div></div>
              )}
            </div>
            <div
              className={clx("grid grid-cols-2 w-full gap-x-4", {
                "grid-cols-1!": isSimple,
              })}
            >
              {!isSimple && (
                <Button
                  onClick={open}
                  variant="secondary"
                  className="w-full"
                  data-testid="mobile-actions-button"
                >
                  <div className="flex items-center justify-between w-full">
                    <span>
                      {variant
                        ? Object.values(options).join(" / ")
                        : "Select Options"}
                    </span>
                    <ChevronDown />
                  </div>
                </Button>
              )}
              <Button
                onClick={handleAddToCart}
                disabled={!inStock || !variant}
                className="w-full"
                isLoading={isAdding}
                data-testid="mobile-cart-button"
              >
                {!variant
                  ? "Select variant"
                  : !inStock
                  ? "Out of stock"
                  : "Add to cart"}
              </Button>
            </div>
          </div>
        </Transition>
      </div>
      <Transition appear show={state} as={Fragment}>
        <Dialog as="div" className="relative z-75" onClose={close}>
          <Transition.Child
            as={Fragment}
            enter="ease-out duration-300"
            enterFrom="opacity-0"
            enterTo="opacity-100"
            leave="ease-in duration-200"
            leaveFrom="opacity-100"
            leaveTo="opacity-0"
          >
            <div className="fixed inset-0 bg-ui-fg-base/40 backdrop-blur-xs" />
          </Transition.Child>

          <div className="fixed bottom-0 inset-x-0">
            <div className="flex min-h-full h-full items-center justify-center text-center">
              <Transition.Child
                as={Fragment}
                enter="ease-out duration-300"
                enterFrom="opacity-0"
                enterTo="opacity-100"
                leave="ease-in duration-200"
                leaveFrom="opacity-100"
                leaveTo="opacity-0"
              >
                <Dialog.Panel
                  className="w-full h-full transform overflow-hidden text-left flex flex-col gap-y-3"
                  data-testid="mobile-actions-modal"
                >
                  <div className="w-full flex justify-end pr-6">
                    <button
                      onClick={close}
                    className="bg-ui-bg-base w-12 h-12 rounded-full text-ui-fg-base flex justify-center items-center"
                      data-testid="close-modal-button"
                    >
                      <X />
                    </button>
                  </div>
                  <div className="bg-ui-bg-base px-6 py-12">
                    {(product.variants?.length ?? 0) > 1 && (
                      <div className="flex flex-col gap-y-6">
                        {(product.options || []).map((option) => {
                          return (
                            <div key={option.id}>
                              <OptionSelect
                                option={option}
                                current={options[option.id]}
                                updateOption={updateOptions}
                                title={option.title ?? ""}
                                disabled={optionsDisabled}
                              />
                            </div>
                          )
                        })}
                      </div>
                    )}
                  </div>
                </Dialog.Panel>
              </Transition.Child>
            </div>
          </div>
        </Dialog>
      </Transition>
    </>
  )
}

export default MobileActions
