// storefront-nuxt/app/pages/[countryCode]/checkout.vue
<script setup lang="ts">
definePageMeta({
  layout: 'checkout'
})

useSeoMeta({
  title: 'Checkout'
})

const { cart } = useCart()
const { customer } = useCustomer()

if (!cart.value) {
  throw createError({
    statusCode: 404,
    statusMessage: 'Cart not found'
  })
}

const checkoutCart = cart.value
</script>

<template>
  <div class="grid grid-cols-1 small:grid-cols-[1fr_416px] content-container gap-x-40 py-12">
    <CheckoutForm
      :cart="checkoutCart"
      :customer="customer"
    />
    <CheckoutSummary :cart="checkoutCart" />
  </div>
</template>

// storefront-next/src/app/[countryCode]/(checkout)/checkout/page.tsx
import { retrieveCart } from "@lib/data/cart"
import { retrieveCustomer } from "@lib/data/customer"
import PaymentWrapper from "@modules/checkout/components/payment-wrapper"
import CheckoutForm from "@modules/checkout/templates/checkout-form"
import CheckoutSummary from "@modules/checkout/templates/checkout-summary"
import { Metadata } from "next"
import { notFound } from "next/navigation"

export const metadata: Metadata = {
  title: "Checkout",
}

type Props = {
  searchParams: Promise<{
    step?: string
  }>
}

export default async function Checkout(props: Props) {
  const cart = await retrieveCart()

  if (!cart) {
    return notFound()
  }

  const customer = await retrieveCustomer()
  const searchParams = await props.searchParams

  return (
    <div className="grid grid-cols-1 small:grid-cols-[1fr_416px] content-container gap-x-40 py-12">
      <PaymentWrapper cart={cart}>
        <CheckoutForm
          cart={cart}
          customer={customer}
          initialStep={searchParams.step}
        />
      </PaymentWrapper>
      <CheckoutSummary cart={cart} />
    </div>
  )
}
