// storefront-next/src/modules/account/components/order-overview/index.tsx
"use client"

import { Button } from "@medusajs/ui"

import OrderCard from "../order-card"
import LocalizedClientLink from "@modules/common/components/localized-client-link"
import { HttpTypes } from "@medusajs/types"

const OrderOverview = ({
  orders,
  countryCode,
}: {
  orders: HttpTypes.StoreOrder[]
  countryCode: string
}) => {
  if (orders?.length) {
    return (
      <div className="flex flex-col gap-y-8 w-full">
        {orders.map((o) => (
          <div
            key={o.id}
            className="border-b border-gray-200 pb-6 last:pb-0 last:border-none"
          >
            <OrderCard order={o} countryCode={countryCode} />
          </div>
        ))}
      </div>
    )
  }

  return (
    <div
      className="w-full flex flex-col items-center gap-y-4"
      data-testid="no-orders-container"
    >
      <h2 className="text-large-semi">Nothing to see here</h2>
      <p className="text-base-regular">
        You don&apos;t have any orders yet, let us change that {":)"}
      </p>
      <div className="mt-4">
        <LocalizedClientLink href="/" countryCode={countryCode} passHref>
          <Button data-testid="continue-shopping-button">
            Continue shopping
          </Button>
        </LocalizedClientLink>
      </div>
    </div>
  )
}

export default OrderOverview

// storefront-nuxt/app/components/account/OrderOverview.vue
<script setup lang="ts">
import type { HttpTypes } from '@medusajs/types'

defineProps<{
  orders: HttpTypes.StoreOrder[]
}>()

const countryCode = useCountryCode()
</script>

<template>
  <div>
    <div
      v-if="orders.length"
      class="flex flex-col gap-y-8 w-full"
    >
      <div
        v-for="order in orders"
        :key="order.id"
        class="border-b border-gray-200 pb-6 last:pb-0 last:border-none"
      >
        <AccountOrderCard :order="order" />
      </div>
    </div>
    <div
      v-else
      class="w-full flex flex-col items-center gap-y-4"
      data-testid="no-orders-container"
    >
      <h2 class="text-large-semi">
        Nothing to see here
      </h2>
      <p class="text-base-regular">
        You don't have any orders yet, let us change that :)
      </p>
      <div class="mt-4">
        <NuxtLink :to="`/${countryCode}`">
          <UButton data-testid="continue-shopping-button">
            Continue shopping
          </UButton>
        </NuxtLink>
      </div>
    </div>
  </div>
</template>
