// storefront-nuxt/app/components/checkout/DiscountCode.vue
<script setup lang="ts">
import { convertToLocale } from '~/utils/money'
import { getApiErrorMessage } from '~/utils/api-error'

const { cart, applyPromotions } = useCart()

const isOpen = ref(false)
const code = ref('')
const applying = ref(false)
const error = ref('')

type Promotion = {
  id: string
  code?: string | null
  is_automatic?: boolean
  application_method?: {
    type?: string
    value?: number
    currency_code?: string
  } | null
}

const promotions = computed<Promotion[]>(() => {
  return (cart.value?.promotions ?? []) as Promotion[]
})

const promotionCodes = computed(() =>
  promotions.value
    .map(promotion => promotion.code)
    .filter((value): value is string => !!value)
)

async function handleApply() {
  const nextCode = code.value.trim()
  if (!nextCode) {
    return
  }

  applying.value = true
  error.value = ''

  try {
    await applyPromotions([...promotionCodes.value, nextCode])
    code.value = ''
  } catch (nextError: unknown) {
    error.value = getApiErrorMessage(nextError, 'Failed to apply promotion code')
  } finally {
    applying.value = false
  }
}

async function handleRemove(codeToRemove: string) {
  error.value = ''

  try {
    await applyPromotions(promotionCodes.value.filter(code => code !== codeToRemove))
  } catch (nextError: unknown) {
    error.value = getApiErrorMessage(nextError, 'Failed to remove promotion code')
  }
}
</script>

<template>
  <div class="w-full bg-white flex flex-col">
    <div class="txt-medium">
      <form
        class="w-full mb-5"
        @submit.prevent="handleApply"
      >
        <div class="my-2 flex gap-x-1 items-center">
          <button
            type="button"
            class="txt-medium text-ui-fg-interactive hover:text-ui-fg-interactive-hover"
            data-testid="add-discount-button"
            @click="isOpen = !isOpen"
          >
            Add Promotion Code(s)
          </button>
        </div>

        <div v-if="isOpen">
          <div class="flex w-full gap-x-2">
            <input
              id="promotion-input"
              v-model="code"
              class="size-full h-10 rounded-md border border-ui-border-base px-3 text-sm"
              data-testid="discount-input"
              type="text"
            >
            <UButton
              type="submit"
              variant="outline"
              :loading="applying"
              data-testid="discount-apply-button"
            >
              Apply
            </UButton>
          </div>

          <CheckoutErrorMessage
            :error="error"
            data-testid="discount-error-message"
          />
        </div>
      </form>

      <div
        v-if="promotions.length > 0"
        class="w-full flex items-center"
      >
        <div class="flex flex-col w-full">
          <h3 class="txt-medium mb-2">
            Promotion(s) applied:
          </h3>

          <div
            v-for="promotion in promotions"
            :key="promotion.id"
            class="mb-2 flex w-full max-w-full items-center justify-between"
            data-testid="discount-row"
          >
            <p class="txt-small-plus flex w-4/5 items-baseline gap-x-1 pr-1">
              <span
                class="truncate"
                data-testid="discount-code"
              >
                <UBadge
                  :color="promotion.is_automatic ? 'success' : 'neutral'"
                  size="sm"
                >
                  {{ promotion.code }}
                </UBadge>
                (
                <template
                  v-if="promotion.application_method?.value !== undefined && promotion.application_method.currency_code"
                >
                  {{
                    promotion.application_method.type === 'percentage'
                      ? `${promotion.application_method.value}%`
                      : convertToLocale({
                        amount: promotion.application_method.value,
                        currency_code: promotion.application_method.currency_code
                      })
                  }}
                </template>
                )
              </span>
            </p>
            <button
              v-if="!promotion.is_automatic && promotion.code"
              type="button"
              class="flex items-center"
              data-testid="remove-discount-button"
              @click="handleRemove(promotion.code)"
            >
              <UIcon
                name="i-lucide-trash-2"
                class="size-4"
              />
              <span class="sr-only">
                Remove discount code from order
              </span>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// storefront-vinext/src/modules/checkout/components/discount-code/index.tsx
"use client"

import { Badge, Heading, Input, Label, Text, Tooltip } from "@medusajs/ui"
import React, { useActionState } from "react";

import { applyPromotions, submitPromotionForm } from "@lib/data/cart"
import { convertToLocale } from "@lib/util/money"
import { InformationCircleSolid } from "@medusajs/icons"
import { HttpTypes } from "@medusajs/types"
import Trash from "@modules/common/icons/trash"
import ErrorMessage from "../error-message"
import { SubmitButton } from "../submit-button"

type DiscountCodeProps = {
  cart: HttpTypes.StoreCart & {
    promotions: HttpTypes.StorePromotion[]
  }
}

const DiscountCode: React.FC<DiscountCodeProps> = ({ cart }) => {
  const [isOpen, setIsOpen] = React.useState(false)

  const { items = [], promotions = [] } = cart
  const removePromotionCode = async (code: string) => {
    const validPromotions = promotions.filter(
      (promotion) => promotion.code !== code
    )

    await applyPromotions(
      validPromotions.filter((p) => p.code === undefined).map((p) => p.code!)
    )
  }

  const addPromotionCode = async (formData: FormData) => {
    const code = formData.get("code")
    if (!code) {
      return
    }
    const input = document.getElementById("promotion-input") as HTMLInputElement
    const codes = promotions
      .filter((p) => p.code === undefined)
      .map((p) => p.code!)
    codes.push(code.toString())

    await applyPromotions(codes)

    if (input) {
      input.value = ""
    }
  }

  const [message, formAction] = useActionState(submitPromotionForm, null)

  return (
    <div className="w-full bg-ui-bg-base flex flex-col">
      <div className="txt-medium">
        <form action={(a) => addPromotionCode(a)} className="w-full mb-5">
          <Label className="flex gap-x-1 my-2 items-center">
            <button
              onClick={() => setIsOpen(!isOpen)}
              type="button"
              className="txt-medium text-ui-fg-interactive hover:text-ui-fg-interactive-hover"
              data-testid="add-discount-button"
            >
              Add Promotion Code(s)
            </button>

            {/* <Tooltip content="You can add multiple promotion codes">
              <InformationCircleSolid color="var(--fg-muted)" />
            </Tooltip> */}
          </Label>

          {isOpen && (
            <>
              <div className="flex w-full gap-x-2">
                <Input
                  className="size-full"
                  id="promotion-input"
                  name="code"
                  type="text"
                  autoFocus={false}
                  data-testid="discount-input"
                />
                <SubmitButton
                  variant="secondary"
                  data-testid="discount-apply-button"
                >
                  Apply
                </SubmitButton>
              </div>

              <ErrorMessage
                error={message}
                data-testid="discount-error-message"
              />
            </>
          )}
        </form>

        {promotions.length > 0 && (
          <div className="w-full flex items-center">
            <div className="flex flex-col w-full">
              <Heading className="txt-medium mb-2">
                Promotion(s) applied:
              </Heading>

              {promotions.map((promotion) => {
                return (
                  <div
                    key={promotion.id}
                    className="flex items-center justify-between w-full max-w-full mb-2"
                    data-testid="discount-row"
                  >
                    <Text className="flex gap-x-1 items-baseline txt-small-plus w-4/5 pr-1">
                      <span className="truncate" data-testid="discount-code">
                        <Badge
                          color={promotion.is_automatic ? "green" : "grey"}
                          size="small"
                        >
                          {promotion.code}
                        </Badge>{" "}
                        (
                        {promotion.application_method?.value !== undefined &&
                          promotion.application_method.currency_code !==
                            undefined && (
                            <>
                              {promotion.application_method.type ===
                              "percentage"
                                ? `${promotion.application_method.value}%`
                                : convertToLocale({
                                    amount: Number(
                                      promotion.application_method.value
                                    ),
                                    currency_code:
                                      promotion.application_method
                                        .currency_code,
                                  })}
                            </>
                          )}
                        )
                        {/* {promotion.is_automatic && (
                          <Tooltip content="This promotion is automatically applied">
                            <InformationCircleSolid className="inline text-ui-fg-subtle" />
                          </Tooltip>
                        )} */}
                      </span>
                    </Text>
                    {!promotion.is_automatic && (
                      <button
                        className="flex items-center"
                        onClick={() => {
                          if (!promotion.code) {
                            return
                          }

                          removePromotionCode(promotion.code)
                        }}
                        data-testid="remove-discount-button"
                      >
                        <Trash size={14} />
                        <span className="sr-only">
                          Remove discount code from order
                        </span>
                      </button>
                    )}
                  </div>
                )
              })}
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

export default DiscountCode
