// storefront-next/src/modules/common/components/line-item-unit-price/index.tsx
import { convertToLocale } from "@lib/util/money"
import { HttpTypes } from "@medusajs/types"
import { clx } from "@medusajs/ui"

type LineItemUnitPriceProps = {
  item: HttpTypes.StoreCartLineItem | HttpTypes.StoreOrderLineItem
  style?: "default" | "tight"
  currencyCode: string
}

const LineItemUnitPrice = ({
  item,
  style = "default",
  currencyCode,
}: LineItemUnitPriceProps) => {
  const { total, original_total } = item
  const currentTotal = total ?? 0
  const originalTotal = original_total ?? 0
  const quantity = item.quantity || 1
  const hasReducedPrice = currentTotal < originalTotal

  const percentage_diff = Math.round(
    originalTotal > 0 ? ((originalTotal - currentTotal) / originalTotal) * 100 : 0
  )

  return (
    <div className="flex flex-col text-ui-fg-muted justify-center h-full">
      {hasReducedPrice && (
        <>
          <p>
            {style === "default" && (
              <span className="text-ui-fg-muted">Original: </span>
            )}
            <span
              className="line-through"
              data-testid="product-unit-original-price"
            >
              {convertToLocale({
                amount: originalTotal / quantity,
                currency_code: currencyCode,
              })}
            </span>
          </p>
          {style === "default" && (
            <span className="text-ui-fg-interactive">-{percentage_diff}%</span>
          )}
        </>
      )}
      <span
        className={clx("text-base-regular", {
          "text-ui-fg-interactive": hasReducedPrice,
        })}
        data-testid="product-unit-price"
      >
        {convertToLocale({
          amount: currentTotal / quantity,
          currency_code: currencyCode,
        })}
      </span>
    </div>
  )
}

export default LineItemUnitPrice

// storefront-nuxt/app/components/common/LineItemUnitPrice.vue
<script setup lang="ts">
import { convertToLocale } from '~/utils/money'

const props = defineProps<{
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  item: any
  styleType?: 'default' | 'tight'
  currencyCode: string
}>()

const style = computed(() => props.styleType ?? 'default')
const hasReducedPrice = computed(() => props.item.total < props.item.original_total)
const percentageDiff = computed(() =>
  Math.round(((props.item.original_total - props.item.total) / props.item.original_total) * 100)
)
</script>

<template>
  <div class="flex flex-col text-ui-fg-muted justify-center h-full">
    <template v-if="hasReducedPrice">
      <p>
        <span
          v-if="style === 'default'"
          class="text-ui-fg-muted"
        >Original: </span>
        <span
          class="line-through"
          data-testid="product-unit-original-price"
        >
          {{ convertToLocale({ amount: item.original_total / item.quantity, currency_code: currencyCode }) }}
        </span>
      </p>
      <span
        v-if="style === 'default'"
        class="text-ui-fg-interactive"
      >-{{ percentageDiff }}%</span>
    </template>
    <span
      :class="['text-base-regular', hasReducedPrice ? 'text-ui-fg-interactive' : '']"
      data-testid="product-unit-price"
    >
      {{ convertToLocale({ amount: item.total / item.quantity, currency_code: currencyCode }) }}
    </span>
  </div>
</template>
