// storefront-next/src/modules/layout/components/country-select/index.tsx
"use client"

import {
  Listbox,
  ListboxButton,
  ListboxOption,
  ListboxOptions,
  Transition,
} from "@headlessui/react"
import { Fragment, useEffect, useMemo, useState } from "react"
import ReactCountryFlag from "react-country-flag"

import { StateType } from "@lib/hooks/use-toggle-state"
import { useParams, usePathname } from "next/navigation"
import { updateRegion } from "@lib/data/cart"
import { HttpTypes } from "@medusajs/types"

type CountryOption = {
  country: string
  region: string
  label: string
}

type CountrySelectProps = {
  toggleState: StateType
  regions: HttpTypes.StoreRegion[]
}

const CountrySelect = ({ toggleState, regions }: CountrySelectProps) => {
  const [current, setCurrent] = useState<CountryOption | undefined>(undefined)

  const { countryCode } = useParams()
  const currentPath = usePathname().split(`/${countryCode}`)[1]

  const { state, close } = toggleState

  const options = useMemo(() => {
    return regions
      ?.map((r) => {
        return r.countries?.map((c) => ({
          country: c.iso_2,
          region: r.id,
          label: c.display_name,
        }))
      })
      .flat()
      .filter((option): option is CountryOption => {
        return !!option?.country && !!option.label
      })
      .sort((a, b) => (a?.label ?? "").localeCompare(b?.label ?? ""))
  }, [regions])

  useEffect(() => {
    if (countryCode) {
      const option = options?.find((o) => o?.country === countryCode)
      setCurrent(option)
    }
  }, [options, countryCode])

  const handleChange = (option: CountryOption) => {
    updateRegion(option.country, currentPath)
    close()
  }

  return (
    <div>
      <Listbox
        as="span"
        onChange={handleChange}
        defaultValue={
          countryCode
            ? options?.find((o) => o?.country === countryCode)
            : undefined
        }
      >
        <ListboxButton className="py-1 w-full">
          <div className="txt-compact-small flex items-start gap-x-2">
            <span>Shipping to:</span>
            {current && (
              <span className="txt-compact-small flex items-center gap-x-2">
                {/* @ts-ignore */}
                <ReactCountryFlag
                  svg
                  style={{
                    width: "16px",
                    height: "16px",
                  }}
                  countryCode={current.country ?? ""}
                />
                {current.label}
              </span>
            )}
          </div>
        </ListboxButton>
        <div className="flex relative w-full min-w-[320px]">
          <Transition
            show={state}
            as={Fragment}
            leave="transition ease-in duration-150"
            leaveFrom="opacity-100"
            leaveTo="opacity-0"
          >
            <ListboxOptions
              className="absolute -bottom-[calc(100%-36px)] left-0 xsmall:left-auto xsmall:right-0 max-h-[442px] overflow-y-scroll z-900 bg-white drop-shadow-md text-small-regular uppercase text-black no-scrollbar rounded-rounded w-full"
              static
            >
              {options?.map((o, index) => {
                return (
                  <ListboxOption
                    key={index}
                    value={o}
                    className="py-2 hover:bg-gray-200 px-3 cursor-pointer flex items-center gap-x-2"
                  >
                    {/* @ts-ignore */}
                    <ReactCountryFlag
                      svg
                      style={{
                        width: "16px",
                        height: "16px",
                      }}
                      countryCode={o?.country ?? ""}
                    />{" "}
                    {o?.label}
                  </ListboxOption>
                )
              })}
            </ListboxOptions>
          </Transition>
        </div>
      </Listbox>
    </div>
  )
}

export default CountrySelect

// storefront-nuxt/app/components/layout/CountrySelect.vue
<script setup lang="ts">
const route = useRoute()
const countryCode = computed(() => route.params.countryCode as string)
const { regions } = useRegion()

const isOpen = ref(false)

const options = computed(() => {
  if (!regions.value) return []
  return regions.value
    .flatMap((r: any) =>
      (r.countries ?? []).map((c: any) => ({
        country: c.iso_2,
        region: r.id,
        label: c.display_name
      }))
    )
    .sort((a: any, b: any) => (a.label ?? '').localeCompare(b.label ?? ''))
})

interface CountryOption {
  country: string
  region: string
  label: string
}

const current = computed(() => options.value.find((o: CountryOption) => o.country === countryCode.value))

const handleChange = (option: CountryOption) => {
  const currentPath = route.path.split(`/${countryCode.value}`)[1] || ''
  navigateTo(`/${option.country}${currentPath}`)
  isOpen.value = false
}
</script>

<template>
  <div>
    <button
      class="py-1 w-full"
      @click="isOpen = !isOpen"
    >
      <div class="txt-compact-small flex items-start gap-x-2">
        <span>Shipping to:</span>
        <span
          v-if="current"
          class="txt-compact-small flex items-center gap-x-2"
        >
          {{ current.label }}
        </span>
      </div>
    </button>
    <div class="flex relative w-full min-w-[320px]">
      <Transition
        leave-active-class="transition ease-in duration-150"
        leave-from-class="opacity-100"
        leave-to-class="opacity-0"
      >
        <ul
          v-if="isOpen"
          class="absolute -bottom-[calc(100%-36px)] left-0 xsmall:left-auto xsmall:right-0 max-h-[442px] overflow-y-scroll z-[900] bg-white drop-shadow-md text-small-regular uppercase text-black no-scrollbar rounded-rounded w-full"
        >
          <li
            v-for="o in options"
            :key="o.country"
            class="py-2 hover:bg-gray-200 px-3 cursor-pointer flex items-center gap-x-2"
            @click="handleChange(o)"
          >
            {{ o.label }}
          </li>
        </ul>
      </Transition>
    </div>
  </div>
</template>
