// storefront-next/src/modules/layout/components/side-menu/index.tsx
"use client"

import { Popover, PopoverPanel, Transition } from "@headlessui/react"
import { ArrowRightMini, XMark } from "@medusajs/icons"
import { Text, clx, useToggleState } from "@medusajs/ui"
import { Fragment } from "react"

import LocalizedClientLink from "@modules/common/components/localized-client-link"
import CountrySelect from "../country-select"
import { HttpTypes } from "@medusajs/types"

const SideMenuItems = {
  Home: "/",
  Store: "/store",
  Account: "/account",
  Cart: "/cart",
}

const SideMenu = ({
  regions,
  countryCode,
}: {
  regions: HttpTypes.StoreRegion[] | null
  countryCode?: string
}) => {
  const toggleState = useToggleState()

  return (
    <div className="h-full">
      <div className="flex items-center h-full">
        <Popover className="h-full flex">
          {({ open, close }) => (
            <>
              <div className="relative flex h-full">
                <Popover.Button
                  data-testid="nav-menu-button"
                  className="relative h-full flex items-center transition-all ease-out duration-200 focus:outline-hidden hover:text-ui-fg-base"
                >
                  Menu
                </Popover.Button>
              </div>

              <Transition
                show={open}
                as={Fragment}
                enter="transition ease-out duration-150"
                enterFrom="opacity-0"
                enterTo="opacity-100 backdrop-blur-2xl"
                leave="transition ease-in duration-150"
                leaveFrom="opacity-100 backdrop-blur-2xl"
                leaveTo="opacity-0"
              >
                <PopoverPanel className="flex flex-col absolute w-full pr-4 sm:pr-0 sm:w-1/3 2xl:w-1/4 sm:min-w-min h-[calc(100vh-1rem)] z-30 inset-x-0 text-sm text-ui-fg-on-color m-2 backdrop-blur-2xl">
                  <div
                    data-testid="nav-menu-popup"
                    className="flex flex-col h-full bg-[rgba(3,7,18,0.5)] rounded-rounded justify-between p-6"
                  >
                    <div className="flex justify-end" id="xmark">
                      <button data-testid="close-menu-button" onClick={close}>
                        <XMark />
                      </button>
                    </div>
                    <ul className="flex flex-col gap-6 items-start justify-start">
                      {Object.entries(SideMenuItems).map(([name, href]) => {
                        return (
                          <li key={name}>
                            <LocalizedClientLink
                              href={href}
                              countryCode={countryCode}
                              className="text-3xl leading-10 hover:text-ui-fg-disabled"
                              onClick={close}
                              data-testid={`${name.toLowerCase()}-link`}
                            >
                              {name}
                            </LocalizedClientLink>
                          </li>
                        )
                      })}
                    </ul>
                    <div className="flex flex-col gap-y-6">
                      <div
                        className="flex justify-between"
                        onMouseEnter={toggleState.open}
                        onMouseLeave={toggleState.close}
                      >
                        {regions && (
                          <CountrySelect
                            toggleState={toggleState}
                            regions={regions}
                          />
                        )}
                        <ArrowRightMini
                          className={clx(
                            "transition-transform duration-150",
                            toggleState.state ? "-rotate-90" : ""
                          )}
                        />
                      </div>
                      <Text className="flex justify-between txt-compact-small">
                        © {new Date().getFullYear()} Medusa Store. All rights
                        reserved.
                      </Text>
                    </div>
                  </div>
                </PopoverPanel>
              </Transition>
            </>
          )}
        </Popover>
      </div>
    </div>
  )
}

export default SideMenu

// storefront-nuxt/app/components/layout/SideMenu.vue
<script setup lang="ts">
const route = useRoute()
const countryCode = computed(() => route.params.countryCode as string)
const isOpen = ref(false)

const menuItems = [
  { name: 'Home', href: '/' },
  { name: 'Store', href: '/store' },
  { name: 'Account', href: '/account' },
  { name: 'Cart', href: '/cart' }
]
</script>

<template>
  <div class="h-full">
    <div class="flex items-center h-full">
      <button
        data-testid="nav-menu-button"
        class="relative h-full flex items-center transition-all ease-out duration-200 focus:outline-none hover:text-ui-fg-base"
        @click="isOpen = true"
      >
        Menu
      </button>
    </div>

    <ClientOnly>
      <USlideover
        v-model:open="isOpen"
        side="left"
        :ui="{ content: 'small:max-w-md w-full' }"
      >
        <template #content>
          <div
            data-testid="nav-menu-popup"
            class="flex flex-col h-full bg-[rgba(3,7,18,0.5)] backdrop-blur-2xl justify-between p-6 text-white"
          >
            <div class="flex justify-end">
              <button
                data-testid="close-menu-button"
                @click="isOpen = false"
              >
                <UIcon
                  name="i-lucide-x"
                  class="w-6 h-6"
                />
              </button>
            </div>
            <ul class="flex flex-col gap-6 items-start justify-start">
              <li
                v-for="item in menuItems"
                :key="item.name"
              >
                <NuxtLink
                  :to="`/${countryCode}${item.href}`"
                  class="text-3xl leading-10 hover:text-ui-fg-disabled"
                  :data-testid="`${item.name.toLowerCase()}-link`"
                  @click="isOpen = false"
                >
                  {{ item.name }}
                </NuxtLink>
              </li>
            </ul>
            <div class="flex flex-col gap-y-6">
              <div
                class="flex justify-between items-center group"
              >
                <LayoutCountrySelect />
                <UIcon
                  name="i-lucide-arrow-right"
                  class="w-5 h-5 transition-transform duration-150 group-hover:-rotate-90"
                />
              </div>
              <p class="flex justify-between txt-compact-small">
                © {{ new Date().getFullYear() }} Medusa Store. All rights reserved.
              </p>
            </div>
          </div>
        </template>
      </USlideover>
    </ClientOnly>
  </div>
</template>
