// storefront-vinext/src/modules/cart/components/cart-item-select/index.tsx
"use client"

import { IconBadge, clx } from "@medusajs/ui"
import {
  SelectHTMLAttributes,
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
  useState,
} from "react"

import ChevronDown from "@modules/common/icons/chevron-down"

type NativeSelectProps = {
  placeholder?: string
  errors?: Record<string, unknown>
  touched?: Record<string, unknown>
} & Omit<SelectHTMLAttributes<HTMLSelectElement>, "size">

const CartItemSelect = forwardRef<HTMLSelectElement, NativeSelectProps>(
  ({ placeholder = "Select...", className, children, ...props }, ref) => {
    const innerRef = useRef<HTMLSelectElement>(null)
    const [isPlaceholder, setIsPlaceholder] = useState(false)

    useImperativeHandle<HTMLSelectElement | null, HTMLSelectElement | null>(
      ref,
      () => innerRef.current
    )

    useEffect(() => {
      if (innerRef.current && innerRef.current.value === "") {
        setIsPlaceholder(true)
      } else {
        setIsPlaceholder(false)
      }
    }, [innerRef.current?.value])

    return (
      <div>
        <IconBadge
          onFocus={() => innerRef.current?.focus()}
          onBlur={() => innerRef.current?.blur()}
          className={clx(
            "relative flex items-center txt-compact-small border text-ui-fg-base group",
            className,
            {
              "text-ui-fg-subtle": isPlaceholder,
            }
          )}
        >
          <select
            ref={innerRef}
            {...props}
            className="appearance-none bg-transparent border-none px-4 transition-colors duration-150 focus:border-ui-border-base outline-hidden w-16 h-16 items-center justify-center"
          >
            <option disabled value="">
              {placeholder}
            </option>
            {children}
          </select>
          <span className="absolute flex pointer-events-none justify-end w-8 group-hover:animate-pulse">
            <ChevronDown />
          </span>
        </IconBadge>
      </div>
    )
  }
)

CartItemSelect.displayName = "CartItemSelect"

export default CartItemSelect

// storefront-nuxt/app/components/cart/CartItemSelect.vue
<script setup lang="ts">
defineProps<{
  modelValue: string | number
  placeholder?: string
  disabled?: boolean
}>()

defineEmits<{
  (e: 'update:modelValue' | 'change', value: string): void
}>()
</script>

<template>
  <div class="relative flex items-center rounded-md border border-ui-border-base bg-white text-ui-fg-base txt-compact-small">
    <select
      :value="String(modelValue)"
      :disabled="disabled"
      class="h-10 w-14 appearance-none border-none bg-transparent px-3 pr-8 text-sm outline-hidden disabled:cursor-not-allowed"
      @change="
        (event) => {
          const value = (event.target as HTMLSelectElement).value
          $emit('update:modelValue', value)
          $emit('change', value)
        }
      "
    >
      <option
        v-if="placeholder"
        disabled
        value=""
      >
        {{ placeholder }}
      </option>
      <slot />
    </select>
    <span class="pointer-events-none absolute right-2 text-ui-fg-subtle">
      <UIcon
        name="i-lucide-chevron-down"
        class="w-4 h-4"
      />
    </span>
  </div>
</template>
